export enum Methods {
  INT_RUCHAN_KULLANIM_LISTE = 'INT_RUCHAN_KULLANIM_LISTE',
  INT_RUCHAN_KULLANIM_ISLEM = 'INT_RUCHAN_KULLANIM_ISLEM',
  INT_MUSTERI_HISSE_EMANET_CIKIS_STOK_LISTESI = 'INT_MUSTERI_HISSE_EMANET_CIKIS_STOK_LISTESI',
}
